version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: smalmunif
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: assessment_db
    ports:
      - "5432:5432"
    volumes:
      - demo_pg_data:/var/lib/postgresql/data
    networks:
      - demo_network

  assessment_app:
    image: demo-app
    container_name: assessment_app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/assessment_db
      SPRING_DATASOURCE_USERNAME: smalmunif
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - demo_network

networks:
  demo_network:

volumes:
  demo_pg_data: